### ISSUE TITLE
Is there any method to work well without error on the browser?

### ISSUE THREAD

**Issue by JeongJun-Lee** [iursevla/ionic3-PreDB#1]
Hello, thank you for your great tutorial.
I confirmed this works well on the real device. But on the browser, this error will happen like below.

![image](https://user-images.githubusercontent.com/11474775/32589392-0247dd76-c536-11e7-8716-d1b49896163d.png)

I wonder there is any method to work well  without error on the browser?

**Comment by iursevla** [comment]
In the browser you don't have access to cordova, so it shows that error.
To use this or any plugin on the browser you must "mock" it, this is create a fake plugin 
See: [Automating mocks Ionic 3 ](https://www.joshmorony.com/automating-mocks-in-ionic-native-3-x/) and the [first video](https://www.youtube.com/watch?v=SENbR9g7ExQ) that is isnside that post.
Anything else let me know.

**Comment by JeongJun-Lee** [comment]
Thank you for your kind answer. I got a insight from you. And I'll attach a useful tutorial link for Ionic 3 sqlite mocking, which I found it on the web.

https://www.techiediaries.com/mocking-native-sqlite-plugin/
