### ISSUE TITLE
Can we insert db file into www directory automatically with Ionic build process?

### ISSUE THREAD

**Issue by JeongJun-Lee** [iursevla/ionic3-PreDB#2]
Thank you for your great tutorial.
Can we insert db file into www directory automatically with Ionic build process?

**Comment by iursevla** [comment]
What you want is to  have your database in your desktop (for example) and copy it with ionic build? 
I guess you can, using copy script from [@ionic/app-scripts](https://ionicframework.com/docs/developer-resources/app-scripts/). 
Anything else let me know.

**Comment by JeongJun-Lee** [comment]
Thank you for your kind answer. I got a insight from you. I'll try it by modifying webpack script.
