### ISSUE TITLE
If the pre-populated db grows continually, should the db file be re-located to other external storage after APK is installed?

### ISSUE THREAD

**Issue by JeongJun-Lee** [iursevla/ionic3-PreDB#3]
Like the title, the pre-populated db file will be grown by inserting massive data continually. In that case, should the db file be re-located to other external storage after APK is installed?
If so, could you me a trick for it?

**Comment by iursevla** [comment]
That depends on what you want. Other external storage you mean other database or you mean move the database to a server instead of storing it on the device?

**Comment by JeongJun-Lee** [comment]
Once Apk is installed, can it grow in the internal storge of device until the storage is full? If it's full, can I move the db file to external storage like sdcard and then should I have to re-open it with a new path like /sdcard/mydata.db/ ?

**Comment by iursevla** [comment]
> Once Apk is installed, can it grow in the internal storge of device until the storage is full?

There's probably a limit for the .db size. See [StackOverflow](https://stackoverflow.com/a/3540587/),

> an I move the db file to external storage like sdcard and then should I have to re-open it with a new path like /sdcard/mydata.db/ ?

That i don't know.

**Comment by JeongJun-Lee** [comment]
Thank you for your quick answer.

I found out https://github.com/an-rahulpandey/cordova-plugin-dbcopy. The plugin's description said that "Copy SQLite Database from www folder to default app database location". Does it mean that pre-populated db file in the www directory can not grow in it?

**Comment by iursevla** [comment]
I think it can grow in it. 
But probably it would be better to ask the project creator about that, he knows better than me.

**Comment by JeongJun-Lee** [comment]
I agree with you. Thanks.
