### ISSUE TITLE
Have you ever tried to read the encrypted db file by the pre-populated in Ionic3?

### ISSUE THREAD

**Issue by JeongJun-Lee** [iursevla/ionic3-PreDB#4]
I installed additionally cordova-sqlcipher-adapter plugin to read a encrypted db file, which is encrypted by DB Browser for SQLite. When I tried to open the encrypted db with key option by below code: 

private options = { name: 'pos.db', key: 'test', location: 'default', createFromLocation: 1 };
this.sqlite.create(this.options).then((db: SQLiteObject) => {...}

The db file is opened well, but the table in the db cannot be found.

I also posted this [issue](https://github.com/litehelpers/Cordova-sqlcipher-adapter/issues/58) at cordova-sqlcipher-adapter plugin site.

Thanks.

**Comment by iursevla** [comment]
Sorry can't help you with that, but i'm curious to know the answer.
Please post the answer here when you know.

**Comment by JeongJun-Lee** [comment]
I got the official answer from the author like this.
"This combination is not supported and not expected to work."
