### ISSUE TITLE
App not detecting the file

### ISSUE THREAD

**Issue by mhtchong** [iursevla/ionic3-PreDB#8]
Hi.. I was able to successfully run the app to my phone and the result is as expected.

However, when I tried to use my database file it's telling me this error:

![image](https://user-images.githubusercontent.com/5715613/35481169-5c420a6a-0459-11e8-861b-983be06fc07f.png)

I created my own database using the SQLite Studio, exported my tables in .sql format and renamed it to .db. 

I then removed the platform in the project. Pasted the file to www folder and changed the necessary details in the creation of database. 

After doing so, I added the android platform back, build, and run. I tried everything, it doesn't seem to detect my file. I keep on encountering the issue above.

**Comment by iursevla** [comment]
@mhtchong  Are you sure it's not a problem from said file? 
Try to use [DB Browser for SQLite](http://sqlitebrowser.org) and see if it works.
